
# 订阅相关定义
SUBSCR_TYPES = (TYPE_LIST, TYPE_STR, RULE_MATCH) = (1, 2, 3)
SUBSCR_TYPE_MAP = {
    TYPE_LIST: '列表',
    TYPE_STR: '文本',
    RULE_MATCH: '规则匹配',
}
SUBSCR_STATES = (STATE_OPEN, STATE_CLOSE) = (1, 2)
SUBSCR_STATE_MAP = {
    STATE_OPEN: '启用',
    STATE_CLOSE: '关闭',
}
MATCH_RULE_STATES = (MATCH_OPEN, MATCH_CLOSE) = (1, 2)
